### PR TITLE
Support for semantic error highlighting in the Playground

### PR DESCRIPTION
**Pull request by dandelion-lowcode**
Semantic errors are clickable and trigger a highlighting of the faulty line.

image

### CODE REVIEW

**Comment by kolovos** [comment]
Could you please check if this works well in the EGX (http://localhost:8000/playground/?egx) and ECL/EML (http://localhost:8000/playground/?eml) examples for you?

**Comment by dandelion-lowcode** [comment]
I have deliberately left those cases out, as it is not possible to discern from the output (say "Line: 20, Reason: mismatched input: 'rule'") which panel does the error refer to. To do so, the request should also send this information if there is any error.

**Comment by kolovos** [comment]
Yes, you're right. Perhaps then for EGX and EML/ECL the hyperlink detector for parse errors should not be activated in the console view at all?

**Comment by dandelion-lowcode** [comment]
@kolovos That should be it. Would you mind building the bundle yourself? I'm having some CLRF/LF git issues.

**Pull request merged**
