### PR TITLE
Flexmi cross-references example

### PR DESCRIPTION
**Pull request by iovinoludovico**
This is an example of Java code resolving cross-references in flexmi models.

### CODE REVIEW

**Comment by iovinoludovico** [comment]
I signed it. Please check it out.

**Comment by kolovos** [comment]
I still see the following error message I'm afraid

image

**Comment by agarciadom** [comment]
The PR includes a `.class` file. Shouldn't we exclude it? /cc @kolovos

**Comment by kolovos** [comment]
@agarciadom Yes, that file should be excluded.

**Comment by kolovos** [comment]
Thanks again for the PR! Given that the code is pretty self-explanatory I've turned this into an [example](https://github.com/eclipse/epsilon/tree/main/examples/org.eclipse.epsilon.examples.flexmi.crossrefs) instead.

**Pull request closed without merging**
