### PR TITLE
Adding support for EMG with an example

### PR DESCRIPTION
**Pull request by dandelion-lowcode**
This PR adds support for EMG in the front-end side of the playground. Check [this other PR](https://github.com/epsilonlabs/playground/pull/2) for the back-end counterpart. 

In particular this adds:
- [x] A 'Model Generation Examples' folder, under which a Petri Net Generation example is added.
- [x] Appropriate panel management for EMG, showing console, ~model,~ metamodel, and resulting generated model graphically.
- [x] Syntax highlighting for EMG.
- [x] An increment of the test suit for the example.
- [x] Templates for Gradle, Maven, Ant (Eclipse), Java (Gradle), and Java (Maven).

What lacks is:
- [ ] A proper EMG *.gif icon. I have used the EPL one in the meantime (in /mkdocs/docs/playground/css/custom.css).
- [ ] Re-bundling the new code -- I still get metro4 problems with webpack on my machine.
- [x] ~I think the Download dialog produces syntactically correct Gradle / Maven / ... artifacts, but `<epsilon.emg>` is either not defined or exposed correctly in `org.eclipse.epsilon.workflow:2.4.0`.~

Preview:
Result

### CODE REVIEW

**Comment by kolovos** [comment]
Many thanks for the PR! Two comments:

- The model panel doesn't make much sense for EMG programs and could be removed
- To fully support EMG in the Playground, we'd also need to implement the ["Download" functionality](https://eclipse.dev/epsilon/doc/articles/playground/#download-your-work) for the language. One complication is that the EMG ANT task has been added in 2.5 so one would either need to modify the [build.gradle/pom.xml templates](https://github.com/eclipse/epsilon-website/tree/master/mkdocs/docs/playground/templates) to use 2.5.0-SNAPSHOT for EMG, or to hold this back until 2.5 is released (hopefully in a few weeks time).

**Comment by dandelion-lowcode** [comment]
@kolovos Thanks for the pointers. I'll try and complete it throughout the week. I will ask you if I have problems along the way.

**Comment by kolovos** [comment]
Now that Epsilon 2.5 has been released, we should change Epsilon versions from `2.5.0-SNAPSHOT` to `2.5.0`.

**Comment by dandelion-lowcode** [comment]
@kolovos Fixed

**Comment by kolovos** [comment]
Thanks! Could you please also rebase https://github.com/dandelion-lowcode/epsilon-website/tree/master and https://github.com/dandelion-lowcode/epsilon-website/tree/bump-to-2.5.0 on top of the latest version of the epsilon-website master branch when you get a chance?

**Comment by dandelion-lowcode** [comment]
@kolovos Thanks. I rebased both. Both PR changes should be now in https://github.com/eclipse/epsilon-website/pull/26.

**Comment by kolovos** [comment]
Merged in https://github.com/eclipse/epsilon-website/commit/54fc7c909caf5af0a8260853359c234cb65764f3

**Pull request closed without merging**
